### Actualizar empresa
POST http://localhost:3000/api/company/update
Content-Type: application/json

{
  "id": "cmgl9reyu0002jcokivyhuxbi",
  "phone": "222222",
  "altEmail": "jp@empresa.com",
  "address": "Calle Falsa 123"
}

