### Crear usuario
POST http://localhost:3000/api/users/create
Content-Type: application/json

{
  "email": "juan.p433d43e45rez@de4xa3f4rmple.com",
  "password": "Secreto0-",
  "twoFactorSecret": "jajaj"
}

### Obtener todos los usuarios
GET http://localhost:3000/api/users/getAll

