version: 2
services:
  - type: web
    name: onboarding-pyme-backend
    env: node
    rootDir: backend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromSecret: database_url