version: "3.8"
services:
  db:
    image: postgres:15
    container_name: db_copy
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passworddb
      POSTGRES_DB: onboarding_creditos
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata_copy:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_copy
    ports:
      - "8081:8080"
