
@LOCAL_URL = http://localhost:3000
@PRODUCTION_URL = https://onboarding-creditos-pymes.onrender.com


### eliminar usuario por email
GET {{LOCAL_URL}}/api/users/deleteByEmail/juan334@hotmail.com

### eliminar todos los usuarios
GET http://localhost:3000/api/users/deleteAll


### Obtener todos los usuarios
GET http://localhost:3000/api/users/getAll


### Crear usuario
POST http://localhost:3000/api/users/create
Content-Type: application/json

{
  "email": "juan334@hotmail.com",
  "password": "Secreto0-",
  "twoFactorSecret": "super-secreto-mal",
  "legalName": "Juan Perez",
  "taxId": "20-22486722-1",
  "phone": "3704768485"
}

### Cambiar contraseña user
POST http://localhost:3000/api/users/changePassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWdxbTIzamkwMDAwamN3b2l5ZDhxeHZzIiwiZW1haWwiOiJqdWFuMzM0QGhvdG1haWwuY29tIiwiaWF0IjoxNzYwNDUwMzU3LCJleHAiOjE3NjEwNTUxNTd9.ZGtNUXwRW9fTHDlzbWa4Z9Hz56gZwZ86sd_SzFAqOkc

{
  "id": "cmguyp3ku0000jch81hy62nbb",
  "oldPassword": "NuevoSecreto0-",
  "newPassword": "Secreto0-"
}


### activar usuario
@TOKEN_ACTIVACION = 83c1182db8b212bf55ec6b3ce72e6d7f95480e6bd08fc780a0b7082750fb5518
GET http://localhost:3000/api/users/activate?token={{TOKEN_ACTIVACION}}&email=juan334@hotmail.com




//////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////

### activar usuario
@TOKEN_ACTIVACION = ffe2554c23f0b307a940a569ff9fd1025e495e569bfb7f65e7d5307822a40540
GET {{PRODUCTION_URL}}/api/users/activate?token={{TOKEN_ACTIVACION}}&email=minuevoemail@gmail.com


### Crear usuario
POST {{PRODUCTION_URL}}/api/users/create
Content-Type: application/json

{
  "email": "juan334@hotmail.com",
  "password": "Secreto0-",
  "twoFactorSecret": "super-secreto-mal",
  "legalName": "Juan Perez",
  "taxId": "20-22486722-1",
  "phone": "3704768485"
}

### activar usuario
GET {{PRODUCTION_URL}}/api/users/activate?token=7d50d0123f1874dc58ed2c6c13199841f1d22a1fb7a82ea51874c05e12d5fe43&email=juan334@hotmail.com

### Obtener todos los usuarios
GET {{PRODUCTION_URL}}/api/users/getAll

### eliminar todos los usuarios
GET {{PRODUCTION_URL}}/api/users/deleteAll

### eliminar todos los usuarios
GET {{PRODUCTION_URL}}/api/users/deleteAll

### eliminar usuario por email
GET {{PRODUCTION_URL}}/api/users/deleteByEmail/minuevoemail@gmail.com
